import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeLangProvider } from "@/providers/theme-lang-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const themeLangScript = `
    try {
      var theme = localStorage.getItem('theme-hex');
      var lang = localStorage.getItem('lang');
      if (theme) {
        document.documentElement.style.setProperty('--color-primary', theme);
      }
      if (lang) {
        document.documentElement.lang = lang;
      }
    } catch (e) {}
  `;

  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <head>
        <script dangerouslySetInnerHTML={{ __html: themeLangScript }} />
      </head>
      <body className="min-h-full flex flex-col">
        <ThemeLangProvider>{children}</ThemeLangProvider>
      </body>
    </html>
  );
}
