name: Branch Protection

on:
  push:
    branches:
      - main
      - staging

jobs:
  protect-branches:
    if: ${{ !startsWith(github.event.head_commit.message, 'revert:') && !startsWith(github.event.head_commit.message, 'ci:') }}
    runs-on: ubuntu-latest
    steps:
      - name: Notify Telegram
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            🚫 DILARANG PUSH LANGSUNG KE BRANCH 🚫

            ${{ github.repository }}

            Oleh: ${{ github.actor }}
            Branch: ${{ github.ref_name }}

            Lakukan pull request untuk menggabungkan perubahan ke main atau staging.

            Silahkan lakukan revert dengan menggunakan `git revert` kemudian push menggunakan commit `revert:<commit-hash>`

      - name: Protect Branches
        run: |
          echo "Langsung push ke main atau staging tidak diperbolehkan!"
          echo "Silakan buat pull request untuk menggabungkan perubahan ke main atau staging."
          exit 1
